!!
!!                 mixedmodesflux.f90
!!    Explanation:
!!     
!!  compile with: > make
!!  usage:        > ./program.exec
!!  clean exec:   > make clean
!!


program computeflux
    use parameters
    use coefficient_equations
    use compute_modeamplitude
    use data_handling
    use math_functions
    !use meridionalcirculation_mod
    use rotationprofile_mod
    use numerical_scheme

  IMPLICIT NONE
  
  !variable declaration
  integer :: ncolumns, nlines, Nsum,i, nsize,jsmallest,NMESA,count,model,dmodel
  integer :: m, lvalue,lsmallest
  integer :: status,modelini,modelend,version,mprofile,ri,rf,mnew,GYRE_var,rot_var
  integer, allocatable :: jarray(:)
  real (DP), allocatable :: summaryfile(:,:), detailfile(:,:), MESAhistory(:,:), MESAprofile(:,:)
  real (DP), allocatable :: coeff(:), F_total(:,:),omega(:),smalldetailfile(:,:)
  real (DP) :: amp_ml, dummyvector(5)!, matrix(5,5), vector(5),result(5)
  character(35) :: dummy

  print*, 'Give initial, final model number, and delta model (e.g., 0 500 10):'
  read*, modelini, modelend, dmodel
  !print*, 'Use simplified eq. (0) or full eq. (1):'
  !read*, version
  version = 0
  if (version /= 0 .AND. version /= 1) then
    print*, 'select only 0 or 1'
    stop
  end if

  !print*, 'Conserve AM (0) or transport AM (1):'
  !read*, rot_var
  rot_var = 0
  if (rot_var /= 0 .AND. rot_var /= 1) then
    print*, 'select only 0 or 1'
    stop
  end if

  GYRE_var=1
  if (rot_var == 1) then
    print*, 'Run with GYRE (0), without GYRE (1) or only GYRE (2):'
    read*, GYRE_var
    if (GYRE_var ==0) then
      status = SYSTEM('rm -r input/*')
    else if (GYRE_var /= 0 .AND. GYRE_var /= 1 .AND. GYRE_var /= 2) then
      print*, 'select only 0, 1 or 2'
      stop
    end if
  end if

  

  !allocate MESA history file
  NMESA = getnlines('MESA/history.data')
  allocate(MESAhistory(67,NMESA), STAT = status)
  IF(status/=0) STOP
  call readfile('MESA/history.data',MESAhistory)
  !modelini = get_modelN(MESAhistory) 
  !modelend = modelini+4!1
  !dmodel = 1




  if (GYRE_var ==2) then
    status = SYSTEM('rm -r input/*')
    do model = modelini,modelend,dmodel
      call insertcol_MESAfile(model,0,dummyvector)
      call runGYRE(model)
    end do
    stop
  end if




  !insert ini rotation profile in MESA file
  call set_variables(MESAhistory,modelini)
  call insertcol_MESAfile(modelini,1,dummyvector)

  open(500, action='write',file = 'AM.txt')
  !loop to get data of each model and run GYRE ---------------------------------------------------------
  do model = modelini,modelend,dmodel

    !obtain radius of radiative region from MESA profile N2
    !mprofile = getnlines('MESA/profile.data.GYRE') !!changed
    mprofile = getnlines('MESA/profile'//trim(string(model))//'.data.GYRE')
    allocate(MESAprofile(19,mprofile+5))
    !open(301, action='read',file = 'MESA/profile.data.GYRE') !!changed
    open(301, action='read',file = 'MESA/profile'//trim(string(model))//'.data.GYRE')
    read(301,*) dummy
    read(301,*) MESAprofile
    close(301)

    !set general varibables of the model
    call set_variables(MESAhistory,modelini)

    call getradiativeR(ri,rf,MESAprofile)
    print*, 'Rrad = ', MESAprofile(2,ri),'Rconv = ' ,MESAprofile(2,rf)

    if (rot_var==1) then
    
      if (GYRE_var == 0) then
        call runGYRE(model)
      end if

      !allocate the GYRE summary file array
      Nsum = getnlines('input/model_'//trim(string(model))//'/summary.txt')
      allocate(summaryfile(14,Nsum), STAT = status)
      IF(status/=0) STOP
      call readfile('input/model_'//trim(string(model))//'/summary.txt',summaryfile)

      !use all the files generated by GYRE except l=0
      count = 0
      do i=1,Nsum
        if (int(summaryfile(8,i)) == 0) then
          count = count + 1
        end if
      end do
      nsize = Nsum - count
      allocate(jarray(nsize), STAT = status)
      IF(status/=0) STOP
  
      do i=1,nsize
        jarray(i) = int(summaryfile(7,i+count))
      end do

      ncolumns = 19 !number of columns of GYRE detail file
      call getsmallestfile(summaryfile,jarray,jsmallest, nlines,model) ! determine smallest file
      allocate(F_total(3,nlines),smalldetailfile(ncolumns,nlines),STAT=status)
      IF(status/=0) STOP
      lsmallest = int(summaryfile(8,jsmallest))
      call readfile('input/model_'//trim(string(model))//'/detail.l'//trim(string(lsmallest))//&
      &'.j'//trim(string(jsmallest))//'.txt',smalldetailfile)

      F_total(2,:) = 0.

      open(50,action='write',file='output/amp_'//trim(string(model))//'.txt')
      !loop to compute J dot ---------------------------------------------------------------------------------
      do i=1,nsize
        lvalue = int(summaryfile(8,jarray(i)))
        m=getnlines('input/model_'//trim(string(model))//'/detail.l'//trim(string(lvalue))//'.j'//trim(string(jarray(i)))//'.txt')
        allocate(detailfile(ncolumns,m),coeff(m), STAT = status)
        IF(status/=0) STOP
        call readfile('input/model_'//trim(string(model))//'/detail.l'//trim(string(lvalue))//&
        &'.j'//trim(string(jarray(i)))//'.txt',detailfile)
        
        coeff = 0.
        amp_ml = 0.
        if (version==1) then
          call calculate_gwaves(detailfile,m,summaryfile,jarray(i),coeff,MESAprofile)
          !call calculate_coefficients(detailfile,m,summaryfile,jarray(i),coeff,MESAprofile)
        else if(version==0) then
          !call calculate_gwaves_simplified(detailfile,m,summaryfile,jarray(i),coeff,MESAprofile)
          call calculate_simplifiedeq(detailfile,summaryfile,jarray(i),coeff,MESAprofile)
        end if
        call compute_amplitude(detailfile,summaryfile,jarray(i),amp_ml)
        coeff(1)=0.
        F_total(2,:) = F_total(2,:) + interpolate(detailfile(15,:),amp_ml*coeff,m,smalldetailfile(15,:),nlines)
        

        deallocate(detailfile,coeff)
      end do
      close(50)

      !derive gwaves to give jdot
      !F_total(1,:) = smalldetailfile(15,:)*R_star
      !do i=1,nlines-1
      !  F_total(3,i) = - derive(F_total(2,i),F_total(2,i+1),F_total(1,i+1) - F_total(1,i))/(2.*F_total(1,i)**2) 
      !end do
      !F_total(2,:) = F_total(3,:)

      !integrate jdot to give gwaves
      !F_total(1,:) = smalldetailfile(15,:)*R_star
      !do i=2,nlines
      !  F_total(3,i) = -(F_total(2,i-1)*F_total(1,i-1)**2 + F_total(2,i)*F_total(1,i)**2)*(F_total(1,i) - F_total(1,i-1))
      !end do
      !F_total(2,:) = F_total(3,:)

      !Add jdot to the next shell
      !do i=4,nlines
      !  F_total(3,i) = F_total(2,i) + abs(F_total(2,i-1))
      !end do
      !do i=4,nlines
      !  F_total(2,i) = F_total(3,i)
      !end do

      call getradiativeR(ri,rf,MESAprofile)
      F_total(1,:) = smalldetailfile(15,:)*R_star/MESAprofile(2,rf) !radius normalized by base of convection zone
      F_total(3,:) = smalldetailfile(3,:) !mass
    

      !save output
      open(300, action='write',file='output/total_flux_'//trim(string(model))//'.txt')
      call printMatrix(F_total, 3, nlines,300)
      close(300)  

    end if
    
    !!Produce rotation profile
    mnew = 5+getnlines('MESA/profile'//trim(string(model+dmodel))//'.data.GYRE')
    allocate(omega(mnew))
    if (rot_var == 0) then
      !!call rotation_profile(F_total,MESAprofile,omega,model+dmodel,mnew)
      !call rotation_profile_implicit(F_total,MESAprofile,omega,model+dmodel,mnew)
      !call rotation_profile_explicit(MESAprofile,omega,model+dmodel,mnew)
      call rotation_profile_CN_radiative(MESAprofile,omega,model+dmodel,mnew)
      !deallocate(F_total,smalldetailfile,summaryfile,jarray)
    else if (rot_var == 3) then
      call rot_profile_conserveAM(MESAprofile,omega,model+dmodel,mnew)
    end if
    call insertcol_MESAfile(model+dmodel,3,omega)
    
    !free the memory
    deallocate(MESAprofile,omega)
    

  end do
  close(500)

  deallocate(MESAhistory)

end program computeflux
